services:
  cktgnn:
    build: .
    volumes:
      - ./OCB:/app/OCB
      - ./results:/app/results
      - pip-cache:/root/.cache/pip:rw
    # Override the default command with the full training command
    command: python main.py --epochs 300 --save-appendix _cktgnn --model CktGNN --hs 301 

volumes:
  pip-cache: 