services:
  cktgnn:
    build: .
    platform: linux/arm64
    environment:
      - OPENBLAS_NUM_THREADS=4
      - MKL_NUM_THREADS=4
      - OMP_NUM_THREADS=4
      - VECLIB_MAXIMUM_THREADS=4  # Specific to Apple Silicon
      - PYTORCH_ENABLE_MPS=1      # Enable Metal Performance Shaders
    deploy:
      resources:
        limits:
          cpus: '8'    # Use more cores if available on M2 Max
          memory: 12G  # Increase if you have headroom
    volumes:
      - ./OCB:/app/OCB
      - ./results:/app/results
      - pip-cache:/root/.cache/pip:rw
    # Override the default command with the full training command
    command: >
      python main.py 
      --epochs 5 
      --save-appendix _test 
      --model CktGNN 
      --hs 301        # Original benchmark size
      --num-workers 2
      --batch-size 128

volumes:
  pip-cache: 